apiVersion: v1
kind: Pod
metadata:
  name: spotify-pod
  namespace: front-end-app
  labels:
    app: spotify-ui
spec:
  containers:
    - name: spotify-ui
      image: aryanraj2400/spotify-clone
      ports:
        - containerPort: 80
